# Generated by Django 4.2.11 on 2024-04-09 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование меню')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание меню')),
                ('base_url', models.CharField(blank=True, max_length=100, verbose_name='Ссылка на меню')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование пункта меню')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание пункта меню')),
                ('link_url', models.CharField(help_text='URL', max_length=100, verbose_name='URL')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainmenu.menu')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='mainmenu.menuitems')),
            ],
        ),
    ]
